name: Build & Publish (Pack build folder)
on:
  workflow_dispatch:  # 仅手动触发

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y build-essential mingw-w64 tar wget make bzip2 zip
          sudo apt install -y gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu

      - name: Build Windows
        run: |
          chmod +x build-for-windows.sh
          ./build-for-windows.sh

      - name: Build Linux
        run: |
          chmod +x build-for-linux.sh
          ./build-for-linux.sh

      # 显示编译结果
      - name: Show build folder structure
        run: ls -lhR build/

      # 直接打包整个 build 文件夹
      - name: Zip full build directory
        run: zip -r build-all.zip build/

      # 发布打包好的 zip
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: SNANDer-CH347 完整编译包
          files: build-all.zip
          overwrite: true
