name: Build Application for All Platforms

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  publish:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # WINDOWS
          - artifact_name: ./artifact/x86/snander.exe
            asset_name: SNANDer-Windows-32bit.exe

          - artifact_name: ./artifact/x64/snander.exe
            asset_name: SNANDer-Windows-64bit.exe

          # LINUX
          - artifact_name: ./artifact/linux-x64/snander
            asset_name: SNANDer-Linux-x64

          - artifact_name: ./artifact/linux-armv7/snander
            asset_name: SNANDer-Linux-armv7

          - artifact_name: ./artifact/linux-arm64/snander
            asset_name: SNANDer-Linux-arm64

    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Prepare Compilation Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get install -y pkg-config mingw-w64 tar wget make bzip2
          sudo -E apt-get install -y gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu

      - name: Build Windows
        run: |
          chmod +x build-for-windows.sh
          ./build-for-windows.sh

      - name: Build Linux
        run: |
          chmod +x build-for-linux.sh
          ./build-for-linux.sh

      - name: Prepare Artifact
        run: |
          mkdir -p ./artifact/
          cp -rf ./build/x86         ./artifact/
          cp -rf ./build/x64         ./artifact/
          cp -rf ./build/linux-x64    ./artifact/
          cp -rf ./build/linux-armv7  ./artifact/
          cp -rf ./build/linux-arm64  ./artifact/

          ls -lh ./artifact/

      - name: Publish Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref_name }}
          overwrite: true
